# Generated by Django 4.2.21 on 2025-06-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('durations', models.CharField(max_length=255)),
                ('prices', models.CharField(max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.city')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
            ],
        ),
        migrations.CreateModel(
            name='User_developed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(max_length=64)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_code', models.IntegerField(null=True, unique=True)),
                ('secret_token', models.CharField(max_length=64, null=True, unique=True)),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('start_time', models.DateTimeField(null=True)),
                ('stop_time', models.DateTimeField(null=True)),
                ('price', models.FloatField(null=True)),
                ('card_number', models.CharField(max_length=64, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.zone'),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Chalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user_developed'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=64, unique=True)),
                ('Service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
