# Generated by Django 4.2.20 on 2025-03-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totems',
            new_name='Totem',
        ),
        migrations.AlterModelOptions(
            name='totem',
            options={'verbose_name': 'Totem'},
        ),
    ]
