# Generated by Django 4.2.20 on 2025-03-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_totems_totem_alter_totem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location_address', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='totem',
            options={},
        ),
        migrations.RemoveField(
            model_name='totem',
            name='location',
        ),
        migrations.AddField(
            model_name='totem',
            name='durations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='totem',
            name='prices',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='totem',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking'),
        ),
    ]
