# Generated by Django 5.1.7 on 2025-04-15 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_parking_alter_totem_options_remove_totem_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parking',
            name='location_address',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='totem',
            name='durations',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='totem',
            name='prices',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
                ('totem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.totem')),
            ],
        ),
        migrations.CreateModel(
            name='User_developed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user_developed'),
        ),
    ]
