# Generated by Django 5.1.7 on 2025-04-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_car_alter_parking_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car')),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking')),
            ],
        ),
    ]
