# Generated by Django 5.1.7 on 2025-04-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_chalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('durations', models.CharField(max_length=255)),
                ('prices', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='totem',
            name='durations',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='prices',
        ),
        migrations.AddField(
            model_name='parking',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
        migrations.AddField(
            model_name='parking',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
    ]
