# Generated by Django 5.1.7 on 2025-04-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_city_service_provider_remove_totem_durations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='name',
        ),
    ]
