# Generated by Django 5.1.7 on 2025-04-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_parking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='totem',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking', unique=True),
        ),
    ]
