# Generated by Django 5.1.7 on 2025-04-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_parking_name_alter_totem_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
