# Generated by Django 5.1.7 on 2025-04-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_totem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='name',
        ),
    ]
