# Generated by Django 5.1.7 on 2025-04-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_parking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='chalk',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='chalk',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='car',
        ),
        migrations.AddField(
            model_name='chalk',
            name='plate_number',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='plate_number',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.city'),
        ),
        migrations.AddField(
            model_name='totem',
            name='location_address',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
