# Generated by Django 5.1.7 on 2025-04-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_totem_parking_remove_chalk_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='totem',
        ),
    ]
