# Generated by Django 5.1.7 on 2025-04-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_ticket_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location_address',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_provider',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
