# Generated by Django 5.2 on 2025-04-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_ticket_city_ticket_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chalk',
            name='issued_time',
        ),
        migrations.RemoveField(
            model_name='chalk',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='city',
            name='durations',
        ),
        migrations.RemoveField(
            model_name='city',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='city',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='issued_time',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='totem',
            name='identity_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('durations', models.CharField(max_length=255)),
                ('prices', models.CharField(max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.city')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.zone'),
        ),
    ]
