# Generated by Django 5.2 on 2025-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_fine_car_fine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='issued_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
