# Generated by Django 5.2 on 2025-04-16 20:21

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_chalk_car_chalk_issued_time_chalk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='totem',
            field=models.IntegerField(null=True, verbose_name=pages.models.Totem),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_developed',
            field=models.IntegerField(null=True, verbose_name=pages.models.User_developed),
        ),
    ]
