# Generated by Django 5.2 on 2025-04-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_ticket_car_ticket_duration_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_developed',
        ),
    ]
