# Generated by Django 5.2 on 2025-04-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_ticket_user_developed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='totem',
        ),
    ]
