# Generated by Django 5.2 on 2025-04-16 20:32

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_ticket_totem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='identity_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='totem',
            field=models.IntegerField(null=True, verbose_name=pages.models.Totem),
        ),
    ]
