# Generated by Django 5.2 on 2025-04-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_totem_identity_number_ticket_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='identity_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='totem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.totem'),
        ),
    ]
