# Generated by Django 5.2 on 2025-04-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_totem_identity_code_alter_ticket_totem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='identity_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
