# Generated by Django 5.2 on 2025-04-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_totem_identity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='identity_code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totem',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.parking'),
        ),
    ]
