# Generated by Django 5.2 on 2025-04-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_totem_identity_code_alter_totem_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='totem',
        ),
        migrations.AlterField(
            model_name='totem',
            name='identity_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
