# Generated by Django 5.2 on 2025-04-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_ticket_totem_alter_totem_identity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_time',
        ),
    ]
