# Generated by Django 5.2 on 2025-04-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_ticket_car_remove_ticket_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.car'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='totem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.totem'),
        ),
    ]
