# Generated by Django 5.2 on 2025-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_ticket_car_ticket_duration_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_done',
            field=models.BooleanField(default=0),
        ),
    ]
