# Generated by Django 5.2 on 2025-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_ticket_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
