# Generated by Django 5.2 on 2025-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='secret_token',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
