# Generated by Django 5.2 on 2025-05-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_totem_secret_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_done',
        ),
    ]
