# Generated by Django 5.2 on 2025-05-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_ticket_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.zone'),
        ),
    ]
