# Generated by Django 5.2 on 2025-05-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_ticket_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Zone',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.parking'),
        ),
    ]
