# Generated by Django 5.2 on 2025-05-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_remove_ticket_zone_ticket_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Parking',
        ),
    ]
