# Generated by Django 5.2 on 2025-05-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_ticket_totem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='totem',
        ),
    ]
