# Generated by Django 5.2 on 2025-05-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_remove_ticket_totem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Parking',
        ),
        migrations.AddField(
            model_name='ticket',
            name='totem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.totem'),
        ),
    ]
