# Generated by Django 5.2 on 2025-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_remove_ticket_parking_ticket_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='card_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
