# Generated by Django 5.2 on 2025-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_remove_ticket_totem_ticket_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
