# Generated by Django 5.2 on 2025-05-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_ticket_stop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
    ]
