# Generated by Django 5.2 on 2025-06-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_controler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chalk',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='user',
        ),
    ]
