# Generated by Django 5.2 on 2025-06-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_remove_chalk_user_remove_fine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='Service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
