# Generated by Django 5.2 on 2025-06-10 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0048_controler_service_provider_alter_ticket_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_code', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='controler',
            new_name='badge',
        ),
    ]
