# Generated by Django 4.2.21 on 2025-06-09 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0048_controler_service_provider_alter_ticket_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='controler',
            new_name='badge',
        ),
    ]
