# Generated by Django 4.2.21 on 2025-06-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_rename_controler_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='group',
        ),
    ]
