# Generated by Django 4.2.21 on 2025-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_remove_badge_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_number',
            field=models.CharField(default=125, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
