# Generated by Django 4.2.21 on 2025-06-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_user_developed_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalk',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
        migrations.AddField(
            model_name='fine',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.service_provider'),
        ),
    ]
